#ifndef VITERBI_ZU4EV_HW_H
#define VITERBI_ZU4EV_HW_H

#include <stdint.h>
#include "xparameters.h"

#define VITERBI_CTRL_BASEADDR      0xA0000000U
#define VITERBI_REG_CONTROL        0x00U
#define VITERBI_REG_ARCH_ID        0x04U
#define VITERBI_REG_SAMPLE_COUNT   0x08U
#define VITERBI_REG_STATUS         0x0CU
#define VITERBI_REG_CYCLE_COUNT    0x10U
#define VITERBI_REG_MISMATCH_COUNT 0x14U
#define VITERBI_REG_DEBUG_SEEN     0x18U
#define VITERBI_REG_DEBUG_EMITTED  0x1CU
#define VITERBI_REG_DEBUG_SVALID   0x20U
#define VITERBI_REG_DEBUG_SREADY   0x24U

#define VITERBI_CTRL_START_MASK      0x00000001U
#define VITERBI_CTRL_SOFT_RESET_MASK 0x00000002U

#define VITERBI_STATUS_DONE_MASK  0x00000001U
#define VITERBI_STATUS_BUSY_MASK  0x00000002U
#define VITERBI_STATUS_ERROR_MASK 0x00000004U

#define VITERBI_DMA_DEVICE_ID XPAR_AXIDMA_0_DEVICE_ID
#define VITERBI_EXPECTED_ARCH_ID 7U

#if defined(XPAR_PSU_DDR_0_S_AXI_BASEADDR)
#define VITERBI_DDR_BASEADDR XPAR_PSU_DDR_0_S_AXI_BASEADDR
#elif defined(XPAR_PSU_DDR_0_BASEADDRESS)
#define VITERBI_DDR_BASEADDR XPAR_PSU_DDR_0_BASEADDRESS
#else
#define VITERBI_DDR_BASEADDR 0x00000000U
#endif

#define VITERBI_TX_BUFFER_BASE (VITERBI_DDR_BASEADDR + 0x01000000U)
#define VITERBI_RX_BUFFER_BASE (VITERBI_DDR_BASEADDR + 0x02000000U)

#define VITERBI_UART_CONSOLE "COM9"

#endif
